# Generated by Django 4.2 on 2023-04-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_remove_commodity_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='image',
        ),
    ]
